version: '3.1'

services:

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: Fiap@2020
      MYSQL_DATABASE: restcovid

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080